import { PrismaPg } from "@prisma/adapter-pg";
// Generated by `pnpm db:generate` from /prisma/schema.prisma — gitignored,
// not committed. Path is "./generated" (not "../generated") because the
// generator's output now lives at packages/db/src/generated — it has to be
// inside src/ to be within tsconfig's rootDir; see the generator block's
// own comment in schema.prisma and CHANGELOG's 2026-07-24 entry.
import { PrismaClient } from "./generated/prisma/client";

/**
 * Reused across hot reloads in dev (a fresh module load in dev would
 * otherwise open a new connection pool on every file save); a single
 * cold-start instance in production/test.
 */
const globalForPrisma = globalThis as unknown as {
  navicorePrisma?: PrismaClient;
};

function createPrismaClient(): PrismaClient {
  const connectionString = process.env.DATABASE_URL;

  if (!connectionString) {
    // packages/config's loadEnv() should already have caught this at process
    // boot — this is a defensive fallback, not the primary validation path.
    throw new Error(
      "DATABASE_URL is not set. It should have been caught by packages/config's " +
        "loadEnv() at process startup — check that main.ts calls it before this " +
        "module is imported.",
    );
  }

  const adapter = new PrismaPg({
    connectionString,
    // Prisma 7's driver adapters use the underlying `pg` pool's own settings,
    // not Prisma 6-era defaults — `pg` has no connection timeout by default,
    // so an unreachable database would otherwise hang a request forever
    // instead of failing fast. See docs/adr/003-orm-and-database.md.
    max: 10,
    connectionTimeoutMillis: 5_000,
  });

  return new PrismaClient({ adapter });
}

export const prisma = globalForPrisma.navicorePrisma ?? createPrismaClient();

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.navicorePrisma = prisma;
}

export { PrismaClient };
export * from "./generated/prisma/client";
